### PR TITLE
Buildsystem rework

### PR DESCRIPTION
**Pull request by gimbas**
After a lot of consideration i decided to implement a build system based on Make, although a meson is modern and clean i don't think it was the right choice for this.

This PR removes the old meson build system and implements a Make based one.

This PR also includes sources for CMSIS core, STM32F1 CMSIS, STM32F1 hal driver by ST.
These are dependencies for the TinyUSB USB stack wich is also included.
These sources should be included in seperate PRs but since I used them to test the buildsystem i didn't.

For now the sources were included manually, but in the future we should make a script to pull them from source, i don't think submodules are good for this because of bloat, version control, and inconsistencies like directory structures.

I will try my best to change the dependencies tinyusb has on the ST HAL to our own HAL in the future.

I plan to depend solely on TinyUSB for the USB stack, we shouldn't need libopencm3.

Directory structure:
/ - 
/targets/ - contais individual example.mk files for each target, the Makefile will use these to list valid targets
/targets/ld/ - contains linker scripts
/targets/generic/ - makefiles that are use in multiple targets
/src - top source and header files, these apply to all targets
/src/target/ - contains an "abstarct" source that will interface with target specific code
/src/target/example/ - contains code specific to the "example" target
/src/example/ - source files for specific module, for example TinyUSB source
/src/al/ - abstraction layer for generic targets, for example STM32F1
/src/cmsis/ - cmsis core and vendor specific cmsis
/build/ - top build directory, each target will have a subdirectory for build files
/build/example-build/ - build directory for "example" target, contains binaries
/build/example-build/obj/ - contais object and dependency files

Make structure:
Makefile
    |
example_target.mk
    |
    | -- generic_a.mk
    | -- generic_b.mk

Makefile is the top, where it does typical makefile stuff, example_target.mk is where we add target specific rules and sources, target being for example rival310 or bluepill, the target makefile then includes generic rules and sources, for example for the stm32f1 family and tinyusb.

you should focus your atencion the following files:
Makefile
targets/bluepill.mk
targets/generic/stm32f1.mk
targets/generic/tinyusb.mk
targets/ld/bluepill.ld
the rest you can mostly ignore (its mostly code pulled from st hal, cmsis and tinyusb/tinyusbexamples, and will be changed and or trimmed/cleaned in the future).

Sorry for the Large and unclean commits, also for the poorly explained changes.

### CODE REVIEW

**Comment by FFY00** [comment]
What is the issue with meson? Could you provide some clarification here?

I don't want any external projects in the repository, they should be in git submodules if needed.

**Comment by gimbas** [comment]
well for starters i don't know meson, and couldn't find how to do certain suff, like including different sources or a differente flashing procedure, depending on the target.
I don't meson brings much to the table in terms of mcu projects anyway.

I like the concept of submodules, but i don't like that they bring over a lot of unnecessary "crap", like examples, and dependencies we already include, like cmsis.
could we keep a "fork" of those seperate projects in a seperate repository? where we could have scripts that pull and cleanup those projects.

**Comment by FFY00** [comment]
> well for starters i don't know meson, and couldn't find how to do certain suff, like including different sources or a differente flashing procedure, depending on the target.
> I don't meson brings much to the table in terms of mcu projects anyway.

Okay, I can help with that. There are several reasons I selected meson, the main ones being maintainability and configurability. Meson is much easier to extend and configure, is a lot more readable and is much much easier to debug. It also provides a lot of command-line configuration.

For ex. to have the flashing procedure depend on the target, we simply declare it based on a variable:
```meson
if something
	run_target('flash',
        command: [st_flash, 'write', bin.full_path(), '0x08000000'],
        depends: bin)
elif something_else
	run_target('flash',
        command: [my_script, 'write', bin.full_path(), '0x08000000'],
        depends: bin)
endif
```

> I like the concept of submodules, but i don't like that they bring over a lot of unnecessary "crap", like examples, and dependencies we already include, like cmsis.
> could we keep a "fork" of those seperate projects in a seperate repository? where we could have scripts that pull and cleanup those projects.

I don't really see a reason for this, we will not be touching those trees. We just provide have a copy locally for the build system to be able to do its thing. You don't need to ever open those folders (I mean, unless you are working on the build system).

**Comment by gimbas** [comment]
It's just a pet peeve i have with submodules, i'll just man up and do it.

I don't know about meson, most of the advantages don't really matter imo, the only thing for me would be readability, but then again, i think what i did with Make pretty readable.

Unless you want to "convert" what i did to meson we should just keep this, we can always change it the future, not having a defined build system has been preventing me from working on this for a while, we are getting close to a working build.

**Comment by gimbas** [comment]
> ```meson
> if something
> 	run_target('flash',
>         command: [st_flash, 'write', bin.full_path(), '0x08000000'],
>         depends: bin)
> elif something_else
> 	run_target('flash',
>         command: [my_script, 'write', bin.full_path(), '0x08000000'],
>         depends: bin)
> endif
> ```

would you do the same for source files? or does meson have another way to handle sources that are target specific

**Comment by FFY00** [comment]
> It's just a pet peeve i have with submodules, i'll just man up and do it.
> 
> I don't know about meson, most of the advantages don't really matter imo, the only thing for me would be readability, but then again, i think what i did with Make pretty readable.
> 
> Unless you want to "convert" what i did to meson we should just keep this, we can always change it the future, not having a defined build system has been preventing me from working on this for a while, we are getting close to a working build.

Sure, we can keep both build systems.

I think its best if we start by getting a working firmware in a `develop` branch (we can make it the default branch if you want) and then when we have a good idea of what needs to be done and how we should structure the project, we can start putting those changes in master.

> > ```meson
> > if something
> > 	run_target('flash',
> >         command: [st_flash, 'write', bin.full_path(), '0x08000000'],
> >         depends: bin)
> > elif something_else
> > 	run_target('flash',
> >         command: [my_script, 'write', bin.full_path(), '0x08000000'],
> >         depends: bin)
> > endif
> > ```
> 
> would you do the same for source files? or does meson have another way to handle sources that are target specific

Yes, you would append the target specific sources to the sources array based on the target.

**Pull request closed without merging**
